### ISSUE TITLE
你好 关于aarch64运行问题

### ISSUE THREAD

**Issue by NikolaCavendish** [KukiSa/Note#1]
我在使用vaultwarden-install.sh时遇到了一些问题，无法运行/usr/bin/vaultwarden的二进制文件
`无法执行二进制文件`
查看文件信息为
`ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, not stripped`
应该是aarch64不支持运行x86_64的二进制文件，是否有什么解决办法

**Comment by KukiSa** [comment]
> 我在使用vaultwarden-install.sh时遇到了一些问题，无法运行/usr/bin/vaultwarden的二进制文件 `无法执行二进制文件` 查看文件信息为 `ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, not stripped` 应该是aarch64不支持运行x86_64的二进制文件，是否有什么解决办法

您好，此脚本应该限定了仅 `x86_64` 架构才能执行，`aarch64` 架构需要修改此脚本引用的 Docker 镜像和 `jq` 命令的相关参数。

**Comment by NikolaCavendish** [comment]
感谢您的回复，我尝试修改了jq的参数和docker-image-extrac的参数为arm64

**Comment by NikolaCavendish** [comment]
感谢您的回复，我尝试修改了jq的参数和docker-image-extrac的参数为arm64，

**Comment by NikolaCavendish** [comment]
感谢您的回复，我尝试修改了jq的参数和docker-image-extrac的参数为arm64，现在二进制文件可以正常运行了。
但运行后出现找不到SQLite的错误，我选择的模式是MySQL。
```
Error loading config:
  SQLite database directory `data` does not exist or is not a directory
```
我的vaultwarden.service中显示的配置也是mysql。
```
[Unit]
Description=Vaultwarden Server
Documentation=https://github.com/dani-garcia/vaultwarden
After=network.target mysqld.service
Requires=mysqld.service

[Service]
User=vaultwarden
Group=vaultwarden
EnvironmentFile=/etc/vaultwarden.env
ExecStart=/usr/bin/vaultwarden
LimitNOFILE=1048576
LimitNPROC=64
PrivateTmp=true
PrivateDevices=true
ProtectHome=true
ProtectSystem=strict
WorkingDirectory=/var/lib/vaultwarden
ReadWriteDirectories=/var/lib/vaultwarden
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```
是docker镜像的原因吗

**Comment by KukiSa** [comment]
> 感谢您的回复，我尝试修改了jq的参数和docker-image-extrac的参数为arm64，现在二进制文件可以正常运行了。 但运行后出现找不到SQLite的错误，我选择的模式是MySQL。
> 
> ```
> Error loading config:
>   SQLite database directory `data` does not exist or is not a directory
> ```
> 
> 我的vaultwarden.service中显示的配置也是mysql。
> 
> ```
> [Unit]
> Description=Vaultwarden Server
> Documentation=https://github.com/dani-garcia/vaultwarden
> After=network.target mysqld.service
> Requires=mysqld.service
> 
> [Service]
> User=vaultwarden
> Group=vaultwarden
> EnvironmentFile=/etc/vaultwarden.env
> ExecStart=/usr/bin/vaultwarden
> LimitNOFILE=1048576
> LimitNPROC=64
> PrivateTmp=true
> PrivateDevices=true
> ProtectHome=true
> ProtectSystem=strict
> WorkingDirectory=/var/lib/vaultwarden
> ReadWriteDirectories=/var/lib/vaultwarden
> AmbientCapabilities=CAP_NET_BIND_SERVICE
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> 是docker镜像的原因吗

请执行 `cat /etc/vaultwarden.env`

**Comment by NikolaCavendish** [comment]
/etc/vaultwarden.env信息如下
```
DATA_FOLDER=/var/lib/vaultwarden/data
DATABASE_URL=mysql://user:tr984hr98thwe@127.0.0.1:3306/bitwarden
IP_HEADER=X-Real-IP
ICON_CACHE_TTL=2592000
ICON_CACHE_NEGTTL=259200
WEB_VAULT_FOLDER=/var/lib/vaultwarden/web-vault
WEB_VAULT_ENABLED=true
ADMIN_TOKEN=/9muHBOjElD2VC+Qx+3bYWmR0OkqO5HrXYTIgcEpzxT6K/hTP+dXuQutPj5UOeM+
DOMAIN=https://bw.examplebitwarden.net
WEBSOCKET_ENABLED=true
WEBSOCKET_ADDRESS=127.0.0.1
WEBSOCKET_PORT=3012
ROCKET_ADDRESS=127.0.0.1
ROCKET_PORT=8181
ROCKET_WORKERS=10
```

**Comment by KukiSa** [comment]
> /etc/vaultwarden.env信息如下
> 
> ```
> DATA_FOLDER=/var/lib/vaultwarden/data
> DATABASE_URL=mysql://user:tr984hr98thwe@127.0.0.1:3306/bitwarden
> IP_HEADER=X-Real-IP
> ICON_CACHE_TTL=2592000
> ICON_CACHE_NEGTTL=259200
> WEB_VAULT_FOLDER=/var/lib/vaultwarden/web-vault
> WEB_VAULT_ENABLED=true
> ADMIN_TOKEN=/9muHBOjElD2VC+Qx+3bYWmR0OkqO5HrXYTIgcEpzxT6K/hTP+dXuQutPj5UOeM+
> DOMAIN=https://bw.examplebitwarden.net
> WEBSOCKET_ENABLED=true
> WEBSOCKET_ADDRESS=127.0.0.1
> WEBSOCKET_PORT=3012
> ROCKET_ADDRESS=127.0.0.1
> ROCKET_PORT=8181
> ROCKET_WORKERS=10
> ```

可能是 aarch64 架构暂不支持 MySQL 连接。

**Comment by NikolaCavendish** [comment]
我查找了一下vaultwarden的rust部分源码，在vaultwarden/src/config.rs中是报错的位置
![image](https://github.com/KukiSa/Note/assets/76593191/918d4054-2784-4729-b4b4-a06daae27b83)
其中from_url方法判断url是mysql:开头就将类型判断为mysql
![image](https://github.com/KukiSa/Note/assets/76593191/058fb43b-74b9-414b-be1a-5d4581247b3d)
正常应该不会出现SQLite database directory的问题，感觉很奇怪。
/etc/vaultwarden.env中的DATABASE_URL好像不满足SQLite的判断条件，不知道为什么会出现这个问题
`DATABASE_URL=mysql://bwus:n2t5PGzT2y5mC3XB@127.0.0.1:3306/bitwarden`

**Comment by KukiSa** [comment]
> 我查找了一下vaultwarden的rust部分源码，在vaultwarden/src/config.rs中是报错的位置 ![image](https://user-images.githubusercontent.com/76593191/267303676-918d4054-2784-4729-b4b4-a06daae27b83.png) 其中from_url方法判断url是mysql:开头就将类型判断为mysql ![image](https://user-images.githubusercontent.com/76593191/267304293-058fb43b-74b9-414b-be1a-5d4581247b3d.png) 正常应该不会出现SQLite database directory的问题，感觉很奇怪。 /etc/vaultwarden.env中的DATABASE_URL好像不满足SQLite的判断条件，不知道为什么会出现这个问题 `DATABASE_URL=mysql://bwus:n2t5PGzT2y5mC3XB@127.0.0.1:3306/bitwarden`

抱歉，这个问题超出了我的知识边界和解释范围，建议向 Vaultwarden 项目提交 issue。

**Comment by NikolaCavendish** [comment]
感谢您的回复，还有一个奇怪的问题，我尝试卸载服务后重新安装
使用
```
if [ -f /var/lib/vaultwarden/version.json ]; then
	rm -rf /var/lib/vaultwarden/
	rm /usr/bin/vaultwarden
	rm /etc/vaultwarden.env
	rm /etc/systemd/system/vaultwarden.service
fi
userdel -r vaultwarden
```
删除卸载相关服务
然后使用vaultwarden-install.sh重新安装，选择SQLite进行安装，依然会出现这个问题。
但是我在多次重装的尝试中成功启动SQLite的服务一次，不知道我的这个卸载指令是否完善，感谢

**Comment by NikolaCavendish** [comment]
![image](https://github.com/KukiSa/Note/assets/76593191/a0fd6543-dbec-41dd-9586-7e04eccc8250)
当我cd到/var/lib/vaultwarden后再执行，似乎可以运行服务了。我设置的端口为8181，但启动后的端口为8000，应该是/etc/vaultwarden.env的环境变量没有生效，按照vaultwarden代码中的默认设置执行了，具体原因不明。
